# Utilise l'image officielle de WildFly
FROM jboss/wildfly:latest

# Copie ton fichier WAR généré dans le dossier de déploiement de WildFly
COPY target/*.war /opt/jboss/wildfly/standalone/deployments/

# Expose le port 8080 pour accéder à l'application
EXPOSE 8080

# Commande pour démarrer WildFly
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]
