# Utiliser l’image officielle de WildFly
FROM jboss/wildfly:latest

# Définir le répertoire de travail dans le container
WORKDIR /opt/jboss/wildfly/standalone/deployments/

# Copier l’application (.war) dans le répertoire de déploiement de WildFly
COPY target/*.war app.war

# Exposer le port par défaut de WildFly
EXPOSE 8080

# Lancer WildFly
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]
